#!/bin/sh

# The MIT License (MIT)

# Copyright (c) 2013 Evan Purkhiser

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Push a nested directory package to AUR4

set -e

if [ $# -lt 1 ]
then
    echo "usage: $(basename $0) <path/to/project>" >&2
    exit -1
fi

git_root=$(realpath "$(git rev-parse --git-dir)/..")/
pkg_path=$(realpath "$1")
pkg_name=$(basename "$pkg_path")

prefix=${pkg_path#$git_root}
branch=aur4/$pkg_name

if [[ ! -d "$pkg_path" || ! -e "${pkg_path}/PKGBUILD" ]]
then
    echo "$pkg_name does not contain a PKGBUILD" >&2
    exit -1
fi

# Split the package into a branch
git subtree split --prefix="$prefix" -b $branch

# Generate .SRCINFO for each commit
git filter-branch -f --tree-filter "mksrcinfo && sed /^#/d -i .SRCINFO" -- $branch

git push ssh://aur@aur.archlinux.org/${pkg_name}.git/ $branch:master
git branch -D $branch
